### PR TITLE
Bump version to 2.1.10

### PR DESCRIPTION
**Pull request by sayeaud**
/reviewers: @hairyhenderson @DongchaoChen

### CODE REVIEW

**Comment by DongchaoChen** [comment]
@sayeaud looks good.

**Comment by hairyhenderson** [comment]
Ack! We need to bump the DockerHub tag too... woulda been best to do that before this merge :(

**Comment by DongchaoChen** [comment]
@hairyhenderson will you push this new image to docker hub for tag 2.1.10

**Comment by sayeaud** [comment]
Everything should already be taken care of.

**Pull request merged**
